kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: user-storage-class
provisioner: kubernetes.io/gce-pd
parameters:
  type: pd-standard
allowedTopologies:
  - matchLabelExpressions:
    - key: topology.kubernetes.io/zone
      values:
        - us-east1-b
