apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: kustomization
resources:
- namespace.yaml
- nfs-persistent-volume.yaml
- nfs-persistent-volume-claim.yaml
- pod-security-policy.yaml
- service-account.yaml
- user-storage-class.yaml
