apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-persistent-volume
spec:
  storageClassName: ""
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteMany
  claimRef:
    namespace: jupyterhub
    name: nfs-persistent-volume-claim
  csi:
    driver: pd.csi.storage.gke.io
    volumeHandle: projects/14018494820688726148/zones/us-east1-b/disks/disk-nfs
    fsType: ext4
