apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-persistent-volume-claim
spec:
  storageClassName: ""
  volumeName: nfs-persistent-volume
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Gi